config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :profiles
  resources :papers, only: [:index, :show, :edit, :update]
  resources :documents
  resources :employees

  namespace :account do
    root to: 'dashboard#show'

    resource :notification_settings, only: [:update]
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_many   :assignments, dependent: :destroy
  has_many   :employees,   dependent: :nullify
  has_many   :documents,   through:   :assignments

  accepts_nested_attributes_for :documents

  def full_profile_naming
    "#{name} (#{id})"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_documents, only: [:new,  :create, :edit,   :update]
  before_action :set_profile,   only: [:show, :edit,   :update, :destroy]

  respond_to :html

  def index
    @profiles = current_user.profiles.order(name: :desc)
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def edit
  end

  def update
    Profiles::UpdateService.new(@profile, profile_params).call
    respond_with(@profile)
  end

  def destroy
    Profiles::DestroyService.new(@profile).call
    respond_with(@profile)
  end

  private

  def set_documents
    @documents = current_user.documents
  end

  def set_profile
    @profile = current_user.profiles.find(params[:id])
  end

  def profile_params
    documents      = current_user.documents.where(id: params[:profile][:document_ids])
    profile_params = params.require(:profile).permit(:name)

    profile_params[:document_ids] = documents.pluck(:id)

    profile_params
  end
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
<% if @profile.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
  <ul>
    <% @profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= f.input :name, autofocus: true %>

    <% if @documents.exists? %>
    <%= f.association :documents, collection: @documents, as: :check_boxes, label_method: :name %>
    <% else %>
    <div>
      <%= link_to 'Créer des documents', new_document_path, class: 'btn btn-warning' %>
    </div>
    <% end %>

    <%= submit_tag 'Valider', class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Annuler', profiles_path, class: "btn btn-default" %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Profil <%= @profile.name %></h1>

    <%= render 'form' %>

  </div>
</div>

app/views/profiles/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Profils</h1>

    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Nom du Profil</th>
          <th>Nb personnel</th>
          <th>Documents</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% if @profiles.exists? %>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.name %></td>
              <td>
                <% if profile.employees.count > 0 %>
                  <p class="text-primary"><%= profile.employees.count %></p>
                <% else %>
                  <p class="text-success">Profil non assigné</p>
                <% end %>
              </td>
              <td><b>Contient  <%= pluralize(profile.document_ids.count, "document") %> : </b>
              <ul class="fa-ul">
                <% profile.documents.each do |document| %>
                  <li><i class="fa fa-caret-right fa-fw"></i><%= document.name %></li>
                <% end %>
              </ul>
              </td>
              <td><%= link_to 'Modifier', edit_profile_path(profile), class: "btn btn-default" %></td>
              <td>
                <% if profile.employees.empty? %>
                  <%= link_to 'Supprimer', profile, method: :delete, data: { confirm: 'Etes-vous sûr ?' } , class: "btn btn-danger" %>
                <% else %>
                  <button type="button" class="btn btn-danger disabled">Supprimer</button>
                <% end %>
                </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6">Aucun profil</td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Nouveau Profil', new_profile_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Nouveau Profil</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-9">
    <h1>Profil <%= @profile.name %></h1>
  </div>

  <div class="col-xs-12 col-md-3">
    <% if @profile.employees.empty? %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <h2>Documents Associés </h2>
    <ul>
      <% @profile.documents.each do |document| %>
        <li> <%= link_to document.name, document %> </li>
      <% end %>
    </ul>

    <%= link_to 'Modifier', edit_profile_path(@profile) , class: "btn btn-primary"%>
    <%= link_to 'Retour Liste', profiles_path , class: "btn btn-default" %>
    <%= link_to "Supprimer", @profile, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-danger" %>
  </div>
</div>