config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :profiles
  resources :papers, only: [:index, :show, :edit, :update]
  resources :documents
  resources :employees

  namespace :account do
    root to: 'dashboard#show'

    resource :notification_settings, only: [:update]
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base


  ## Relationships
  ## ==============================
  belongs_to :profile
  has_many :papers,     dependent: :destroy
  has_many :documents,  through: :papers

  ## Validations
  ## ==============================
  validates :first_name,  presence: true, length: { minimum:3, maximum: 30 }
  validates :last_name,   presence: true, length: { minimum:3, maximum: 30 }
  validates :profile_id,  presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profiles, only: [:new, :create, :edit, :update]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  include PapersHelper

  def index
    @employees = current_user.employees.order(is_active: :desc, last_name: :asc)
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employees::CreateService.new(employee_params).call
    respond_with(@employee)
  end

  def update
    Employees::UpdateService.new(@employee, employee_params).call
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private

  def set_employee
    @employee = current_user.employees.find(params[:id])
  end

  def set_profiles
    @profiles = current_user.profiles
  end

  def employee_params
    profile         = @profiles.find(params[:employee][:profile_id])
    employee_params = params.require(:employee).permit(
      :first_name,
      :is_active,
      :last_name,
      :status
    )

    employee_params[:profile_id] = profile.id

    employee_params
  end
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
<% if @employee.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

  <ul>
    <% @employee.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= f.input :first_name, autofocus: true %>
    <%= f.input :last_name %>
    <%= f.input :is_active %>
    <%= f.association :profile, collection: @profiles %>

    <%= f.button :submit, 'Valider', class: 'btn btn-primary' %>

    <% end %>
    <%= link_to 'Annuler', employees_path, class: "btn btn-default" %>

  </div>
</div>

app/views/employees/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Employé <%= @employee.full_name %></h1>
    <%= render 'form' %>

  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Personnel</h1>

    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Actif</th>
          <th>Nom</th>
          <th>Statut</th>
          <th>Profil</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @employees.exists? %>
          <% @employees.each do |employee| %>
            <tr class='<%= "is_active" if employee.is_active? %>'>
              <td>
                <p class="<%= employee.is_active ? "text-success" : "text-danger"%>">
                  <span class="<%= employee.is_active ? "glyphicon glyphicon-ok" : "glyphicon glyphicon-remove"%> aria-hidden=true>"</span>
                </p>
              </td>
              <td><%= link_to employee.full_name, employee %></td>
              <td>
              <% if employee.papers.where("expiration_date < NOW()").count > 0 %>
                <i class="fa fa-times-circle text-muted"></i>
                <% else %>
                <i class="fa fa-check-circle text-success"></i>
              <% end %>
              </td>
              <td><%= employee.profile.name %></td>
              <td>
                <div class="btn-group">
                  <%= link_to 'Détails', employee, class: "btn btn-default" %></a>
                  <a aria-expanded="false" href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Modifier", edit_employee_path(employee) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Supprimer", employee, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-danger" %></li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="5">Aucun personnel</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= @employees.count %> / <% if current_user.plan == "vip" %>Illimité
    <% elsif current_user.plan == "silver" %>100
    <% elsif current_user.plan == "trial" %>3
    <% end %>
(<%= current_user.plan %>)
  </br>
  <% if ( current_user.plan == "trial" && @employees.count >= 3) %>
    <%= link_to 'Nouveau Personnel', new_employee_path, class: "btn btn-primary disabled" %>
    <% elsif (current_user.plan == 'silver' && @employees.count >= 100) %>
    <%= link_to 'Nouveau Personnel', new_employee_path, class: "btn btn-primary disabled" %>
    <% elsif (current_user.profiles.count <= 0) %>
    <%= link_to 'Nouveau Personnel', new_employee_path, class: "btn btn-primary disabled" %><p class="text-danger">Aucun profil défini</p>
    <% else %>
    <%= link_to 'Nouveau Personnel', new_employee_path, class: "btn btn-primary " %>
    <% end %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Nouvel Employé</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/employees/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-9">
    <h1><%= @employee.full_name %></h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <strong>Statut :</strong>
    <span class="<%= @employee.is_active ? "text-success" : "text-danger"%>">
      <%= @employee.is_active ? "Employé actif" : "Employé inactif"%>
    </span></br>
    <strong>Profil :</strong> <%= @employee.profile.name %>

    <h2>Documents</h2>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Nom du document</th>
          <th>Date d'expiration</th>
        </tr>
      </thead>
      <tbody>
        <% @employee.papers.each do |paper| %>
        <tr>
          <td> <%= link_to paper.document.name, edit_paper_path(paper) %></td>
          <td> <p class="<%= paper_status_css_class(paper) %>"><%= l(paper.expiration_date) %> </p></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Retour Liste', employees_path , class: "btn btn-default" %>
    <%= link_to 'Modifier', edit_employee_path(@employee) , class: "btn btn-primary"%>
    <%= link_to "Supprimer", @employee, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-danger" %>
  </div>
</div>