config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :profiles
  resources :papers, only: [:index, :show, :edit, :update]
  resources :documents
  resources :employees

  namespace :account do
    root to: 'dashboard#show'

    resource :notification_settings, only: [:update]
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  ## Relationships
  ## ==============================
  belongs_to :user

  has_many   :assignments, dependent: :destroy
  has_many   :papers,      dependent: :destroy

  has_many   :profiles,    through:   :assignments

  ## Structure
  ## ==============================
  validates :critical_days, presence: true, numericality: true
  validates :name,          presence: true, length: { minimum: 2, maximum: 50 }
  validates :warning_days,  presence: true, numericality: true

  validate :critical_under_warning

  def full_document_naming
    "#{name} (#{id})"
  end

  def critical_under_warning
    if critical_days > warning_days
      errors.add(:critical_days, "Seuil critique au dessus du seuil alerte")
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @documents = current_user.documents.order(:name)
    respond_with(@documents)
  end

  def show
    respond_with(@document)
  end

  def new
    @document = Document.new
    respond_with(@document)
  end

  def edit
  end

  def create
    @document = current_user.documents.new(document_params)
    @document.save
    respond_with(@document)
  end

  def update
    @document.update(document_params)
    respond_with(@document)
  end

  def destroy
    Documents::DestroyService.new(@document).call
    respond_with(@document)
  end

  private

  def set_document
    @document = current_user.documents.find(params[:id])
  end

  def document_params
    params.require(:document).permit(
      :critical_days,
      :expire_days,
      :name,
      :warning_days
    )
  end
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>
<% if @document.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

  <ul>
    <% @document.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= f.input :name, autofocus: true %>
    <%= f.input :warning_days %>
    <%= f.input :critical_days %>

    <%= f.button :submit, 'Valider', class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Annuler', @document, class: "btn btn-default" %>
  </div>
</div>

app/views/documents/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edition <%= @document.name %></h1>

    <%= render 'form' %>

  </div>
</div>

app/views/documents/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Modèles de Document</h1>

    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Document</th>
          <th>Profils attachés</th>
          <th class="text-warning">Seuil Alerte</th>
          <th class="text-danger">Seuil Critique</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% if @documents.exists? %>
          <% @documents.each do |document| %>
            <tr>
              <td><%= document.name %></td>
              <td>
                <% if document.profiles.count > 0 %>
                  <p class="text-primary"><%= document.profiles.count %></p>
                <% else %>
                  <p class="text-success">Modèle non assigné</p>
                <% end %>
              </td>
              <td class="text-warning"> <%= document.warning_days %> jours </td>
              <td class="text-danger"> <%= document.critical_days %> jours </td>
              <td><%= link_to 'Modifier', edit_document_path(document) , class: "btn btn-default" %></td>
              <td>
                <% if document.profiles.empty? %>
                  <%= link_to 'Supprimer', document, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-danger" %>
                <% else %>
                  <button type="button" class="btn btn-danger disabled">Supprimer</button>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="8">Aucun modèle de document</td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Nouveau modèle de document', new_document_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/documents/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Nouveau modèle de Document</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/documents/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Détails <%= @document.name %></h1>
  </div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>
      <strong>Profils attachés :</strong>
      <%= @document.profiles.count %>
      <p class="text-warning">
      	<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
      	Seuil <b> Warning</b> à <%= @document.warning_days %> jours</p>
      <p class="text-danger">
      	<span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
    	Seuil <b> Critical</b> à <%= @document.critical_days %> jours</p>
    </p>

    <%= link_to 'Modifier', edit_document_path(@document), class: "btn btn-primary"  %>
    <%= link_to 'Retour Liste', documents_path, class: "btn btn-default"  %>
    <% if @document.profiles.empty? %>
        <%= link_to "Supprimer", @document, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>