config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :profiles
  resources :papers, only: [:index, :show, :edit, :update]
  resources :documents
  resources :employees

  namespace :account do
    root to: 'dashboard#show'

    resource :notification_settings, only: [:update]
  end
end

app/views/layouts/slate.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Cerbere App" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <!-- Font Awesome and CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/slate/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "carousel" %>
  <!-- offline mode -->
  <!--<%= stylesheet_link_tag "font-awesome.min" %>
  <%= stylesheet_link_tag "bootstrap.min" %>
  <%= stylesheet_link_tag "bootstrap.slate.min" %>-->

</head>
<body>
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to( image_tag("logo/logosmall.png", border: 0), root_path, class: "navbar-brand") %><span class="navbar-brand">BETA</span>
        <!--<span class="navbar-brand">CerbereApp BETA</span>-->
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

          <% if not user_signed_in? %>
          <li class="<%= 'active' if current_page?(page_path('home')) %>"><%= link_to "Accueil", page_path('home') %></a></li>
          <li class="<%= 'active' if current_page?(page_path('features')) %>"><%= link_to "Fonctionnalités", page_path('features') %></li>
          <li class="<%= 'active' if current_page?(page_path('pricing')) %>"><%= link_to "Abonnements", page_path('pricing') %></li>
          <li class="<%= 'active' if current_page?(page_path('contact')) %>"><%= link_to "Contact", page_path('contact') %></li>
          <% end %>

          <% if user_signed_in? %>
          <li class="<%= 'active' if current_page?(employees_path) %>"><%= link_to "Personnel", employees_path %></li>
          <li class="<%= 'active' if current_page?(profiles_path) %>"><%= link_to "Profils", profiles_path %></li>
          <li class="<%= 'active' if current_page?(papers_path) %>"><%= link_to "Documents", papers_path %></li>
          <li class="<%= 'active' if current_page?(documents_path) %>"><%= link_to "Modèles de document", documents_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="divider"></li>
          <% if user_signed_in? %>
          <li class="divider"></li>
          <li><%= link_to "Mon compte", '/account' %></li>
          <% else %>
          <li><%= link_to "Connexion", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->
  <div class="header">
  </br>
</br>
</div>
<div class="container">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-dismissible alert-<%= message_type %>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= message_type %></strong>
    <%= message %>
  </div>
  <% end %>

  <%= yield %>

  <!--  <%#= debug(params) if Rails.env.development? %> -->
</br>
</div>
<div class='footer'>
<div class='container'>
<div class="well well-lg">
  <div class='row'>
    <div class='col-md-6 col-sm-4 col-xs-6'>
      <h4 class="lead">La société</h4>
      <p><i>Cerbere App</i> est une application web. <%= link_to "consultez nos abonnements", page_path('pricing') %>!</p>
      <p><%= link_to "Nous contacter", page_path('contact') %></p>
      <p>Cerbere App &copy;2015.</p>
    </div>
    <div class='col-md-3 col-sm-2 col-xs-6'>
      <h4>Partenaires</h4>
    </div>

    <div class='col-md-3 col-sm-2 col-xs-6'>
      <h4>Social</h4>
      <a href='http://twitter.com/cerbereapp'><%= image_tag "basic_social/colored/32/square/email.png"%></a>
      <a href='http://twitter.com/cerbereapp'><%= image_tag "basic_social/colored/32/square/twitter.png"%></a>
      <h4>Liens</h4>
        <i class="fa fa-caret-right fa-fw"></i><%= link_to "Accueil", page_path('home') %></br>
        <i class="fa fa-caret-right fa-fw"></i><%= link_to "Fonctionnalités", page_path('features') %></br>
        <i class="fa fa-caret-right fa-fw"></i><%= link_to "Abonnements", page_path('pricing') %></br>
        <i class="fa fa-caret-right fa-fw"></i><%= link_to "Contact", page_path('contact') %>
    </div>
  </div>
</div>
</div>
</div>
<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
<%= javascript_include_tag "application" %>
</body>
</html>